# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_auto_20170718_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(verbose_name='%m/%d/%Y'),
        ),
    ]
